ck: arm64: selecting ANON_INODES by default
to #30401861

The implementation of pidfd_open requires ANON_INODES support,
so selecting it by default

make allnoconfig
make -j64 -s
ld: kernel/fork.o: in function `copy_process.isra.0.part.0':
fork.c:(.text+0x19f4): undefined reference to `anon_inode_getfile'
fork.c:(.text+0x19f4): relocation truncated to fit: R_AARCH64_CALL26
against undefined symbol `anon_inode_getfile'
ld: kernel/pid.o: in function `__arm64_sys_pidfd_open':
pid.c:(.text+0xb28): undefined reference to `anon_inode_getfd'
pid.c:(.text+0xb28): relocation truncated to fit: R_AARCH64_CALL26
against undefined symbol `anon_inode_getfd'

Signed-off-by: Yang, Wei <wei.yang1@linux.alibaba.com>
Reviewed-by: Liguang Zhang <zhangliguang@linux.alibaba.com>