ck: cpuidle: Allow enabling the halt polling on ARM64
fix #32281677

Add cpu.h header file for poll_state.c to fix below building error
on ARM64 architecture.

drivers/cpuidle/poll_state.c:14:22: error:
expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘poll_idle’

Moreover fix the error of missing KVM_HINTS_REALTIME feature on
ARM64 architecture.

Signed-off-by: Baolin Wang <baolin.wang@linux.alibaba.com>
Reviewed-by: luanshi <zhangliguang@linux.alibaba.com>