alinux: mm: fix undefined reference to printk_ratelimit_state
fix #27508738

The variable printk_ratelimit_state is not defined if CONFIG_PRINTK is
not set, but is directly accessed in mm/oom_kill.c without considering
the config.

Consider CONFIG_PRINTK when accessing printk_ratelimit_state in
mm/oom_kill.c.

Fixes: 41a1a9357d03 ("alinux: oom: add ratelimit printk to prevent softlockup")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Xu Yu <xuyu@linux.alibaba.com>
Reviewed-by: zhongjiang-ali <zhongjiang-ali@linux.alibaba.com>
Acked-by: Caspar Zhang <caspar@linux.alibaba.com>