alinux: mm: bring back unevictable.o in obj-y
fix #27508674

The commit 79e7c57a183 ("alinux: mm: fix undefined reference to
mlock_fixup") intends to fix undefined reference to mlock_fixup when
compiling unevictable.o with CONFIG_MMU disabled.

However, it accidentally does not include unevictable.o in the target
obj-y.  This brings unevictable.o back.

Fixes: 79e7c57a183 ("alinux: mm: fix undefined reference to mlock_fixup")
Signed-off-by: Xu Yu <xuyu@linux.alibaba.com>
Reviewed-by: Xunlei Pang <xlpang@linux.alibaba.com>