io_uring: fix build error on arm
Fix the following build error on arm
fs/io-wq.c: In function '__io_worker_unuse':
fs/io-wq.c:158:3: error: implicit declaration of function 'set_fs' [-Werror=implicit-function-declaration]
  158 |   set_fs(KERNEL_DS);
      |   ^~~~~~

Fixes: 1716578fec3d ("io_uring: replace workqueue usage with io-wq")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Xiaoguang Wang <xiaoguang.wang@linux.alibaba.com>