alinux: arm64: fixed arm-cmn build error without ACPI
fix #28929074

fixed build error without ACPI as follow:
drivers/perf/arm-cmn.c:822:12: error: implicit declaration of function 'acpi_evaluate_integer'

Fixes: 42783f7eab6f ("amp: perf: arm_cmn: improve and make it work on 2P.")
Signed-off-by: Zou Cao <zoucao@linux.alibaba.com>
Reviewed-by: luanshi <zhangliguang@linux.alibaba.com>