anolis: arm64: Fix building errors with allnoconfig
ANBZ: #47

The ARM64 architecture already supports node memblock no matter
if NUMA is on or off. Thus we can remove the NUMA dependency to
remove below allnoconfig building errors.

mm/page_alloc.c: In function 'memmap_init':
mm/page_alloc.c:5977:2: error: implicit declaration of function
'for_each_mem_pfn_range'; did you mean 'for_each_mem_range'?
[-Werror=implicit-function-declaration]
 5977 |  for_each_mem_pfn_range(i, nid, &start_pfn, &end_pfn, NULL) {
       |  ^~~~~~~~~~~~~~~~~~~~~~
             |  for_each_mem_range

Fixes: 4b28640aa7bb ("mm: memmap_init: iterate over memblock regions
rather that check each PFN")
Signed-off-by: Baolin Wang <baolin.wang@linux.alibaba.com>
Reviewed-by: luanshi <zhangliguang@linux.alibaba.com>
Signed-off-by: Shile Zhang <shile.zhang@linux.alibaba.com>