alios: jbd2: fix build warning on i386
Fix the following build warning on arch i386:

ld: fs/jbd2/journal.o: in function `jbd2_seq_stats_show':
journal.c:(.text+0x137d): undefined reference to `__udivdi3'

Fixes: 3550da0c6520 ("alios: jbd2: add new "stats" proc file")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Reviewed-by: Jeffle Xu <jefflexu@linux.alibaba.com>
Acked-by: Caspar Zhang <caspar@linux.alibaba.com>