alinux: mm: fix undefined reference to mlock_fixup
fix #27508674

The function mlock_fixup is not defined if CONFIG_MMU is not set, but is
directly invoked by mm/unevictable.c without considering the config.

Make unevictable.o depend on mmu-$(CONFIG_MMU) where the definition of
mlock_fixup locates in.

Fixes: 7d6cb94f148e ("alinux: mm: Pin code section of process in memory")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Xu Yu <xuyu@linux.alibaba.com>
Acked-by: Xunlei Pang <xlpang@linux.alibaba.com>