ck: jbd2: fix build errors
Fix below build errors, 'wait_sum' and 'iowait_sum' need
CONFIG_SCHEDSTATS to be configured.

fs/jbd2/transaction.c: In function 'new_handle':
fs/jbd2/transaction.c:406:51: error: 'struct sched_statistics' has no member named 'wait_sum'
    handle->h_sched_wait_sum = current->se.statistics.wait_sum;
fs/jbd2/transaction.c:407:48: error: 'struct sched_statistics' has no member named 'iowait_sum'
    handle->h_io_wait_sum = current->se.statistics.iowait_sum;

fs/jbd2/transaction.c: In function 'jbd2_journal_stop':
fs/jbd2/transaction.c:1790:38: error: 'struct sched_statistics' has no member named 'wait_sum'
    sched_wait = current->se.statistics.wait_sum -
fs/jbd2/transaction.c:1792:35: error: 'struct sched_statistics' has no member named 'iowait_sum'
    io_wait = current->se.statistics.iowait_sum -

Fixes: 67393bb9f538 ("alinux: jbd2: track slow handle which is preventing transaction committing")
Reviewed-by: Joseph Qi <joseph.qi@linux.alibaba.com>
Signed-off-by: Xiaoguang Wang <xiaoguang.wang@linux.alibaba.com>
Signed-off-by: Hao Xu <haoxu@linux.alibaba.com>
Acked-by: Joseph Qi <joseph.qi@linux.alibaba.com>